language: python
python:
  - "3.6"
  - '2.7'

services:
  - postgresql

before_script:
  - psql -c "create database imager;" -U postgres

env:
  - SECRET_KEY='tandonholderbone' DEBUG=True DB_NAME='imager' DB_HOST='localhost'

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python imagersite/manage.py migrate
  - coverage run imagersite/manage.py test imagersite

after_success:
  - coveralls

notifications:
  email: false